language: bash
dist: trusty
addons:
  apt:
    sources:
      - sourceline: "deb http://archive.ubuntu.com/ubuntu/ trusty-backports universe"
    packages:
      - shellcheck
script:
  - shellcheck $(find . -maxdepth 1 -type f -executable)
