name: docker-build
on:
  pull_request:
  push:
    branches: [main]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build Docker image
        run: |
          docker build . # will run buildx
